
name: Release new version

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-ghpkg:
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
