
name: '{{name}}'
description: '{{desc}}'
branding:
  icon: 'upload-cloud'
  color: 'yellow'
inputs:
  key-id:
    required: true
outputs:
  url:
    description: url
runs:
  using: 'node16'
  main: 'lib/index.js'
